### ISSUE TITLE
Hello, I am a mac user and i cant install .bat file

### ISSUE THREAD

**Issue by fundurian** [GetScatter/scatter-sharp#1]
Hello, I am a mac user and i cant install .bat file

So that leave me to add package to my existing project, so i import package i saw there are 5 .dll file, then i copy your scene and script into my asset folder and when i test run on computer it say "unable to connect to remote server"

I test run again on android phone also same error "unable to connect to remote server"

If i am mac user how do i properly configure it to run?

**Comment by mmcs85** [comment]
There is no timeline yet to add support for building scatter-sharp on Mac.
More information will be posted in due time
