### ISSUE TITLE
Passing unity3d path when running .\build_package_win.bat

### ISSUE THREAD

**Issue by Tondy** [GetScatter/scatter-sharp#12]
Hello

I have been trying to run .\build_package_win.bat when adding scatter to an existing 
project.  I already have the unity package in my project.

Error: Unity path not defined. Please set the UNITY_PATH environment variable to the Unity.exe file, or pass the path as argument

When I run .\build_package_win.bat I get the error above I have tried putting  my unity path 
as argument like is :

.\build_package_win.bat D:\Program Files\Unity3D5\Editor\Unity.exe 

I recieve D:\ does not exist even when it does . Mind you I am running this is my C:\ drive

**Comment by mmcs85** [comment]
Use quotes. ex: .\build_package_win.bat "D:\Program Files\Unity3D5\Editor\Unity.exe"
