### ISSUE TITLE
Unity Web GL Support?

### ISSUE THREAD

**Issue by ARoomWithABue** [GetScatter/scatter-sharp#3]
I loaded the Scatter Sharp example scene in Unity. I've been playing around with the project and tested it on several platforms: OSX, Windows, and WebGL. The OSX and Windows builds worked without issue, but it seems that WebGL has issues connecting to Scatter through socket. Has there been testing done with Web GL already? If so, is there a build configuration that works?  Is Web GL a build target Scatter is interested in supporting?

**Comment by mmcs85** [comment]
Good news! I just released scatter-sharp 2.0 that should support WebGL

https://github.com/GetScatter/scatter-sharp/releases/tag/v2.0.0

Have fun!
