### ISSUE TITLE
Documentation: Add requirement for .NET Core cross-platform development toolset

### ISSUE THREAD

**Issue by dbendt** [GetScatter/scatter-sharp#6]
Thank you for your effort on this library and examples! Was testing this out and found that I needed to install the ".NET Core cross-platform development" toolset in VS2017 to get the build script to run properly. Perhaps adding a note would help avoid the issue I had.

![package](https://user-images.githubusercontent.com/2263036/53373687-0bfc0500-390b-11e9-9015-72962f6cdc7a.png)

**Comment by mmcs85** [comment]
You right. Its always useful to add that tools.
Added a note here: https://github.com/GetScatter/scatter-sharp/blob/master/Unity3D/README.md
Can you post the log of the errors? Just to check exactly where it fails.

Thanks

**Comment by dbendt** [comment]
I think the ```create_plugins.bat``` script just stops here: https://github.com/GetScatter/scatter-sharp/blob/b8a09aca913efec7694f764994edba0505bd2657/Unity3D/create_plugins.bat#L10-L12 since it can't find the executable. So there is no output.

**Comment by mmcs85** [comment]
![image](https://user-images.githubusercontent.com/19377179/53406534-0efe0080-39b2-11e9-8622-6b9bc49a7193.png)

Actualy I can make it work just with the unity module. Might install the build tools as well but it adds more tools to integrate with unity. Can you try to just enable it?

**Comment by dbendt** [comment]
Removed both Game Development with Unity and .NET Core cross-platform development tools. Build script would not complete. Installed Game Development with Unity and attempted build script. Would not complete. Install .NET Core cross-platform development tools and build completed successfully. Some errors issued related to Unit Tests and missing NuGet packages, but works just fine.

**Comment by mmcs85** [comment]
Ok I will add both to the documents
