### ISSUE TITLE
Suggestion: Add timeout or reconnect options to Scatter.Connect()

### ISSUE THREAD

**Issue by dbendt** [GetScatter/scatter-sharp#7]
Currently having an intermittent issue where the web socket opens and no response occurs after the ```42/scatter, ["connected"]``` message. Adding a timeout to the C# task to error gracefully, but it would be nice to specify this to avoid hanging infinitely.

![image](https://user-images.githubusercontent.com/2263036/53589997-a778ba00-3b45-11e9-9064-3d156ca962f9.png)

Successful attempts appear to also include a ```42/scatter,["paired",null]``` message.

![image](https://user-images.githubusercontent.com/2263036/53590136-f6beea80-3b45-11e9-81f9-5031d6c23025.png)

**Comment by mmcs85** [comment]
Made a new release https://github.com/GetScatter/scatter-sharp/releases/tag/v2.0.4 with some fixes to requests timouts and adding a override in each method api to timeout

Note that is possible to configure the default timeout on the ScatterConfigurator now

Paired, null is a normal response after "connected" is to ask for sending pair request
