### ISSUE TITLE
The SDK 'Microsoft.NET.Sdk' specified could not be found. Unity3D

### ISSUE THREAD

**Issue by Tondy** [GetScatter/scatter-sharp#9]
Hello

I am trying to install  Scatter for unity3d.  After running the 

./create_plugins.bat I receive the following errors.

Build FAILED.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
(Build target) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\eos-sharp\EosSharp\EosSharp.Core\EosSharp.Core.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\eos-sharp\EosSharp\EosSharp\EosSharp.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\eos-sharp\EosSharp\EosSharp.Unity3D\EosSharp.Unity3D.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\socketio-sharp\SocketIOSharp\SocketIOSharp\SocketIOSharp.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\socketio-sharp\SocketIOSharp\WebSocketSharp\websocket-sharp\websocket-sharp.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\socketio-sharp\SocketIOSharp\SocketIOSharp.Core\SocketIOSharp.Core.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln.metaproj : error MSB3202: The project file "D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\..\socketio-sharp\SocketIOSharp\SocketIOSharp.Unity3D\SocketIOSharp.Unity3D.csproj" was not found. [D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln]

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp\ScatterSharp.csproj" (default target) (2) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp\ScatterSharp.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests\ScatterSharp.UnitTests.csproj" (default target) (3) ->
(EnsureNuGetPackageBuildImports target) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests\ScatterSharp.UnitTests.csproj(99,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.Unity3D\ScatterSharp.Unity3D.csproj" (default target) (4) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.Unity3D\ScatterSharp.Unity3D.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.Core\ScatterSharp.Core.csproj" (default target) (5) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.Core\ScatterSharp.Core.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests.Core\ScatterSharp.UnitTests.Core.csproj" (default target) (6) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests.Core\ScatterSharp.UnitTests.Core.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests.Unity3D\ScatterSharp.UnitTests.Unity3D.csproj" (default target) (7) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.UnitTests.Unity3D\ScatterSharp.UnitTests.Unity3D.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.sln" (default target) (1) ->
"D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.EosProvider\ScatterSharp.EosProvider.csproj" (default target) (8) ->
  D:\Unity3DEOS\scatter-sharp-master\ScatterCsharp\ScatterSharp\ScatterSharp.EosProvider\ScatterSharp.EosProvider.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk' specified could not be found.

**Comment by mmcs85** [comment]
Hey there,
Can you tell-me what OS, version of Visual studio you using?

Did you follow the Readme prerequisites?
Prerequisite to build
Unity >= 2018.1
Visual Studio 2017+
".NET Core cross-platform development" toolset in VS2017
"Game development with Unity" toolset in VS2017

You also have a unity bundle that you can import with the latest version

**Comment by Tondy** [comment]
Hello

I am using  Windows 10 pro and Visual Studio 2017 and unity3d 2019.1.1. "Game development with Unity" toolset in VS2017 .

**Comment by Tondy** [comment]
> You also have a unity bundle that you can import with the latest version

Hello

I am using Windows 10 pro and Visual Studio 2017 and unity3d 2019.1.1. "Game development with Unity" toolset in VS2017 .

**Comment by mmcs85** [comment]
Clone the project with --recursive flag.
git clone https://github.com/GetScatter/scatter-sharp --recursive
